# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.TextField(default='', max_length=30),
        ),
    ]
