# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 23:02
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
