# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160925_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post_likes',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
